version: '3.8'
services:
  app:
    ports:
      - "8080:8080"
    image: 'challenge:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - DATASOURCE_USER=postgres
      - DATASOURCE_PASSWORD=postgres

  db:
    image: postgres:14.1-alpine
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - "./postgres/data:/var/lib/postgresql/data"