spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE.URL}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}
